version: '3'

volumes:
  psqldata:

services:
  go-graphql-starter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: marcelo
      POSTGRES_PASSWORD: mfsimahe
      POSTGRES_DB: postgres
    volumes:
      - ~/psqldata:/var/lib/postgresql/data
      - ./data/1.0/1_users.sql:/docker-entrypoint-initdb.d/1_usrs.sql
      - ./data/1.0/2_roles.sql:/docker-entrypoint-initdb.d/2_roles.sql
      - ./data/1.0/3_rel_users_roles.sql:/docker-entrypoint-initdb.d/3_rel_users_roles.sql
    ports:
      - "54321:5432"
    restart: unless-stopped